import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import { NextIntlClientProvider } from 'next-intl';
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.css";
import SessionProviderWrapper from "./_Components/SessionProviderWrapper/SessionProviderWrapper";
import { getMessages } from "next-intl/server";
import CheckSession from "./_Components/Auth/CheckSession/CheckSession";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params }: {
  children: React.ReactNode;
  params:Promise<{ locale: string}>;
}) {
  const messages = await getMessages();
  const{locale }=await params;
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'} >
      <body  suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <NextIntlClientProvider messages={messages} >
          <SessionProviderWrapper>
            {/* <CheckSession locale={locale} />   */}
            <main className=" bg-background mb-12">
              {children}
            </main>
          </SessionProviderWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
